# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82cb2cb1384d8727afe78f7650dbbadd20c048c8efa40f3ae5ff6fe7dd1b49afacc8f67855b090b702308fd19f6dbec3f75387da55021cafc17111a1f79a0dca

test:
  secret_key_base: 28a6588b9754f9881be3419d00a0acfc90ad3542841d4402500f430bd23c2ab372541f0e9a094b95f2689553c0a5d0d65b933a2b2d4270eb8d5c387cd7adf8d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
